# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "email"
name = "Email"
url = "mailto://muyang1337@gmail.com"

[social.params]
icon = "mail"

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/muyang1337"

[social.params]
icon = "brand-github"

[[social]]
identifier = "x"
name = "x"
url = "https://x.com/muyang1337"

[social.params]
icon = "brand-x"

[[social]]
identifier = "linkedin"
name = "Linkedin"
url = "https://www.linkedin.com/in/muyang1337/"

[social.params]
icon = "brand-linkedin"
